package icaro.infraestructura.corba.recursos.visualizacion.itfUsoVisualizadorAccesoIDL;


/**
* organizacion/infraestructura/corba/recursos/visualizacion/itfUsoVisualizadorAccesoIDL/_ItfUsoVisualizadorAccesoIDLImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoVisualizadorAccesoIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public abstract class _ItfUsoVisualizadorAccesoIDLImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements icaro.infraestructura.corba.recursos.visualizacion.itfUsoVisualizadorAccesoIDL.ItfUsoVisualizadorAccesoIDL, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _ItfUsoVisualizadorAccesoIDLImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("mostrarVisualizadorAcceso", new java.lang.Integer (0));
    _methods.put ("cerrarVisualizadorAcceso", new java.lang.Integer (1));
    _methods.put ("mostrarMensajeInformacion", new java.lang.Integer (2));
    _methods.put ("mostrarMensajeAviso", new java.lang.Integer (3));
    _methods.put ("mostrarMensajeError", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // organizacion/infraestructura/corba/recursos/visualizacion/itfUsoVisualizadorAccesoIDL/ItfUsoVisualizadorAccesoIDL/mostrarVisualizadorAcceso
       {
         String nombreAgente = in.read_string ();
         String tipoAgente = in.read_string ();
         this.mostrarVisualizadorAcceso (nombreAgente, tipoAgente);
         out = $rh.createReply();
         break;
       }

       case 1:  // organizacion/infraestructura/corba/recursos/visualizacion/itfUsoVisualizadorAccesoIDL/ItfUsoVisualizadorAccesoIDL/cerrarVisualizadorAcceso
       {
         this.cerrarVisualizadorAcceso ();
         out = $rh.createReply();
         break;
       }

       case 2:  // organizacion/infraestructura/corba/recursos/visualizacion/itfUsoVisualizadorAccesoIDL/ItfUsoVisualizadorAccesoIDL/mostrarMensajeInformacion
       {
         String titulo = in.read_string ();
         String mensaje = in.read_string ();
         this.mostrarMensajeInformacion (titulo, mensaje);
         out = $rh.createReply();
         break;
       }

       case 3:  // organizacion/infraestructura/corba/recursos/visualizacion/itfUsoVisualizadorAccesoIDL/ItfUsoVisualizadorAccesoIDL/mostrarMensajeAviso
       {
         String titulo = in.read_string ();
         String mensaje = in.read_string ();
         this.mostrarMensajeAviso (titulo, mensaje);
         out = $rh.createReply();
         break;
       }

       case 4:  // organizacion/infraestructura/corba/recursos/visualizacion/itfUsoVisualizadorAccesoIDL/ItfUsoVisualizadorAccesoIDL/mostrarMensajeError
       {
         String titulo = in.read_string ();
         String mensaje = in.read_string ();
         this.mostrarMensajeError (titulo, mensaje);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:organizacion/infraestructura/corba/recursos/visualizacion/itfUsoVisualizadorAccesoIDL/ItfUsoVisualizadorAccesoIDL:1.0", 
    "IDL:organizacion/infraestructura/corba/patronRecursoSimple/itfUsoRecursoSimpleIDL/ItfUsoRecursoSimpleIDL:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _ItfUsoVisualizadorAccesoIDLImplBase
