package icaro.infraestructura.corba.recursos.visualizacion.itfUsoVisualizadorAccesoIDL;

import organizacion.infraestructura.corba.recursos.visualizacion.itfUsoVisualizadorAccesoIDL.ItfUsoVisualizadorAccesoIDLOperations;


/**
* organizacion/infraestructura/corba/recursos/visualizacion/itfUsoVisualizadorAccesoIDL/ItfUsoVisualizadorAccesoIDL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoVisualizadorAccesoIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public interface ItfUsoVisualizadorAccesoIDL extends ItfUsoVisualizadorAccesoIDLOperations, icaro.infraestructura.corba.patronRecursoSimple.itfUsoRecursoSimpleIDL.ItfUsoRecursoSimpleIDL, org.omg.CORBA.portable.IDLEntity 
{
} // interface ItfUsoVisualizadorAccesoIDL
