//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.18 at 11:40:39 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:icaro:aplicaciones:descripcionOrganizaciones", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package icaro.infraestructura.entidadesBasicas.descEntidadesOrganizacion.jaxb;
