package icaro.infraestructura.corba.recursos.visualizacion.itfUsoVisualizadorTestPersonalidadIDL;

/**
* organizacion/infraestructura/corba/recursos/visualizacion/itfUsoVisualizadorTestPersonalidadIDL/ItfUsoVisualizadorTestPersonalidadIDLHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoVisualizadorTestPersonalidadIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public final class ItfUsoVisualizadorTestPersonalidadIDLHolder implements org.omg.CORBA.portable.Streamable
{
  public icaro.infraestructura.corba.recursos.visualizacion.itfUsoVisualizadorTestPersonalidadIDL.ItfUsoVisualizadorTestPersonalidadIDL value = null;

  public ItfUsoVisualizadorTestPersonalidadIDLHolder ()
  {
  }

  public ItfUsoVisualizadorTestPersonalidadIDLHolder (icaro.infraestructura.corba.recursos.visualizacion.itfUsoVisualizadorTestPersonalidadIDL.ItfUsoVisualizadorTestPersonalidadIDL initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = icaro.infraestructura.corba.recursos.visualizacion.itfUsoVisualizadorTestPersonalidadIDL.ItfUsoVisualizadorTestPersonalidadIDLHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    icaro.infraestructura.corba.recursos.visualizacion.itfUsoVisualizadorTestPersonalidadIDL.ItfUsoVisualizadorTestPersonalidadIDLHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return icaro.infraestructura.corba.recursos.visualizacion.itfUsoVisualizadorTestPersonalidadIDL.ItfUsoVisualizadorTestPersonalidadIDLHelper.type ();
  }

}
