package icaro.infraestructura.corba.recursos.visualizacion.itfUsoVisualizadorTestPersonalidadIDL;


/**
* organizacion/infraestructura/corba/recursos/visualizacion/itfUsoVisualizadorTestPersonalidadIDL/ItfUsoVisualizadorTestPersonalidadIDLOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoVisualizadorTestPersonalidadIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public interface ItfUsoVisualizadorTestPersonalidadIDLOperations  extends icaro.infraestructura.corba.patronRecursoSimple.itfUsoRecursoSimpleIDL.ItfUsoRecursoSimpleIDLOperations
{
  void accionSalir ();
  void mostrarMensajeError (String descripcion);
  void mostrarConfirmacion (String[] textosTest);
  void mostrarVentanaPrincipal (String[] listaAyudas);
  void variaVentanaPrincipal (int panel, String[] listaPreguntas, int[] resultadosPrevios);
  void mostrarResultado (String descripcion, int[] resultados, String[] textosTest);
  void mostrarIncompletitud ();
} // interface ItfUsoVisualizadorTestPersonalidadIDLOperations
