package icaro.infraestructura.corba.recursos.visualizacion.itfUsoVisualizadorTestPersonalidadIDL;


/**
* organizacion/infraestructura/corba/recursos/visualizacion/itfUsoVisualizadorTestPersonalidadIDL/t_textosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoVisualizadorTestPersonalidadIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public final class t_textosHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public t_textosHolder ()
  {
  }

  public t_textosHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = icaro.infraestructura.corba.recursos.visualizacion.itfUsoVisualizadorTestPersonalidadIDL.t_textosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    icaro.infraestructura.corba.recursos.visualizacion.itfUsoVisualizadorTestPersonalidadIDL.t_textosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return icaro.infraestructura.corba.recursos.visualizacion.itfUsoVisualizadorTestPersonalidadIDL.t_textosHelper.type ();
  }

}
