package icaro.infraestructura.corba.entidadesbasicas.mensajeStruct;


/**
* organizacion/infraestructura/corba/entidadesbasicas/mensajeStruct/MensajeStructHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/EntidadesBasicas.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

abstract public class MensajeStructHelper
{
  private static String  _id = "IDL:organizacion/infraestructura/corba/entidadesbasicas/mensajeStruct/MensajeStruct:1.0";

  public static void insert (org.omg.CORBA.Any a, icaro.infraestructura.corba.entidadesbasicas.mensajeStruct.MensajeStruct that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static icaro.infraestructura.corba.entidadesbasicas.mensajeStruct.MensajeStruct extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_wstring_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "clase",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_wstring_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "contenido",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (icaro.infraestructura.corba.entidadesbasicas.mensajeStruct.MensajeStructHelper.id (), "MensajeStruct", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static icaro.infraestructura.corba.entidadesbasicas.mensajeStruct.MensajeStruct read (org.omg.CORBA.portable.InputStream istream)
  {
    icaro.infraestructura.corba.entidadesbasicas.mensajeStruct.MensajeStruct value = new icaro.infraestructura.corba.entidadesbasicas.mensajeStruct.MensajeStruct ();
    value.clase = istream.read_wstring ();
    value.contenido = istream.read_wstring ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, icaro.infraestructura.corba.entidadesbasicas.mensajeStruct.MensajeStruct value)
  {
    ostream.write_wstring (value.clase);
    ostream.write_wstring (value.contenido);
  }

}
