package icaro.infraestructura.corba.entidadesbasicas.eventoStruct;

/**
* organizacion/infraestructura/corba/entidadesbasicas/eventoStruct/EventoStructHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/EntidadesBasicas.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public final class EventoStructHolder implements org.omg.CORBA.portable.Streamable
{
  public icaro.infraestructura.corba.entidadesbasicas.eventoStruct.EventoStruct value = null;

  public EventoStructHolder ()
  {
  }

  public EventoStructHolder (icaro.infraestructura.corba.entidadesbasicas.eventoStruct.EventoStruct initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = icaro.infraestructura.corba.entidadesbasicas.eventoStruct.EventoStructHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    icaro.infraestructura.corba.entidadesbasicas.eventoStruct.EventoStructHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return icaro.infraestructura.corba.entidadesbasicas.eventoStruct.EventoStructHelper.type ();
  }

}
