package icaro.infraestructura.recursosOrganizacion.recursoTrazas.imp.gui;

import icaro.infraestructura.recursosOrganizacion.recursoTrazas.imp.componentes.ControlTrazas;
import icaro.infraestructura.recursosOrganizacion.recursoTrazas.imp.componentes.InfoTraza;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;

import javax.swing.JFrame;

import org.jdesktop.layout.GroupLayout;
import org.jdesktop.layout.LayoutStyle;


/**
 *
 * @author  fmpr
 */
public class PanelTrazasClasificadas extends javax.swing.JFrame {
	private ControlTrazas controlador;

    public PanelTrazasClasificadas(List<String> elementosTrazables,ControlTrazas c) {
        initComponents(elementosTrazables);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.controlador = c;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(List<String> elementosTrazables) {

    	this.addWindowListener(new WindowAdapter()
		{
    		public void windowClosing(WindowEvent e)
    		{
    			cierraVentana();
    		}
		});
    	
    	this.setResizable(false);

        labelVentana = new javax.swing.JLabel();
        tabbedTrazas = new javax.swing.JTabbedPane();
        panelGeneral = new javax.swing.JPanel();
        panelGeneralMensaje = new javax.swing.JPanel();
        labelGeneralMensaje = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaGeneralMensaje = new javax.swing.JTextArea();
        panelInfo = new javax.swing.JPanel();
        panelInfoMensaje = new javax.swing.JPanel();
        labelInfoMensaje = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaInfoMensaje = new javax.swing.JTextArea();
        panelDebug = new javax.swing.JPanel();
        panelDebugMensaje = new javax.swing.JPanel();
        labelDebugMensaje = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        areaDebugMensaje = new javax.swing.JTextArea();
        panelError = new javax.swing.JPanel();
        panelErrorMensaje = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        areaErrorMensaje = new javax.swing.JTextArea();
        panelFatal = new javax.swing.JPanel();
        panelFatalMensaje = new javax.swing.JPanel();
        labelFatalMensaje = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        areaFatalMensaje = new javax.swing.JTextArea();
        separadorZonas = new javax.swing.JSeparator();
        panelAdministracion = new javax.swing.JPanel();
        labelElegirComponente = new javax.swing.JLabel();
        jScrollPanelComponentes = new javax.swing.JScrollPane();
        listaComponentes = new javax.swing.JList(elementosTrazables.toArray());
        this.setTitle("Ventana de Trazas");
        
        botonTerminar = new javax.swing.JButton();

        
        jScrollPanelComponentes.setViewportView(listaComponentes);
        
        
        //Eliminar los mouseListener de la lista de componentes:
        MouseListener[] listeners = listaComponentes.getMouseListeners();
        for (int i=0; i< listeners.length; i++) {
        	listaComponentes.removeMouseListener(listeners[i]);
        }
        
        //añadir el mouseListener a la lista de componentes:
    	 MouseListener mouseListener = new MouseAdapter() {
    	     public void mouseClicked(MouseEvent e) {
    	         if (e.getClickCount() == 2) {
    	             int index = listaComponentes.locationToIndex(e.getPoint());
    	             listaComponentes.setSelectedIndex(index);
    	             controlador.muestraVentanaEspecifica(listaComponentes.getSelectedValue().toString());
    	          }
    	     }
    	 };
    	 
    	 listaComponentes.addMouseListener(mouseListener);
    	 
        
        
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelVentana.setFont(new java.awt.Font("Trebuchet MS", 0, 36));
        labelVentana.setText("                     VENTANA DE TRAZAS");

        labelGeneralMensaje.setFont(new java.awt.Font("Trebuchet MS", 0, 11));
        labelGeneralMensaje.setText("CONTENIDO DEL MENSAJE");

        areaGeneralMensaje.setColumns(20);
        areaGeneralMensaje.setEditable(false);
        areaGeneralMensaje.setRows(5);
        jScrollPane2.setViewportView(areaGeneralMensaje);
        
        
       

        GroupLayout panelGeneralMensajeLayout = new GroupLayout(panelGeneralMensaje);
        panelGeneralMensaje.setLayout(panelGeneralMensajeLayout);
        panelGeneralMensajeLayout.setHorizontalGroup(
            panelGeneralMensajeLayout.createParallelGroup(GroupLayout.LEADING)
            .add(GroupLayout.TRAILING, panelGeneralMensajeLayout.createSequentialGroup()
                .add(panelGeneralMensajeLayout.createParallelGroup(GroupLayout.TRAILING)
                    .add(jScrollPane2, GroupLayout.LEADING, GroupLayout.DEFAULT_SIZE, 565)
                    .add(labelGeneralMensaje, GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelGeneralMensajeLayout.setVerticalGroup(
            panelGeneralMensajeLayout.createParallelGroup(GroupLayout.LEADING)
            .add(panelGeneralMensajeLayout.createSequentialGroup()
                .add(labelGeneralMensaje)
                .addPreferredGap(LayoutStyle.UNRELATED)
                .add(jScrollPane2, GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))
        );

        GroupLayout panelGeneralLayout = new GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(GroupLayout.LEADING)
            .add(panelGeneralMensaje, GroupLayout.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE)
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(GroupLayout.LEADING)
            .add(panelGeneralMensaje, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabbedTrazas.addTab("General", panelGeneral);

        labelInfoMensaje.setFont(new java.awt.Font("Trebuchet MS", 0, 11));
        labelInfoMensaje.setText("CONTENIDO DEL MENSAJE");

        areaInfoMensaje.setColumns(20);
        areaInfoMensaje.setEditable(false);
        areaInfoMensaje.setRows(5);
        jScrollPane4.setViewportView(areaInfoMensaje);

        GroupLayout panelInfoMensajeLayout = new GroupLayout(panelInfoMensaje);
        panelInfoMensaje.setLayout(panelInfoMensajeLayout);
        panelInfoMensajeLayout.setHorizontalGroup(
            panelInfoMensajeLayout.createParallelGroup(GroupLayout.LEADING)
            .add(GroupLayout.TRAILING, panelInfoMensajeLayout.createSequentialGroup()
                .add(panelInfoMensajeLayout.createParallelGroup(GroupLayout.TRAILING)
                    .add(jScrollPane4, GroupLayout.LEADING, GroupLayout.DEFAULT_SIZE, 565)
                    .add(labelInfoMensaje, GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelInfoMensajeLayout.setVerticalGroup(
            panelInfoMensajeLayout.createParallelGroup(GroupLayout.LEADING)
            .add(panelInfoMensajeLayout.createSequentialGroup()
                .add(labelInfoMensaje)
                .addPreferredGap(LayoutStyle.UNRELATED)
                .add(jScrollPane4, GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))
        );

        GroupLayout panelInfoLayout = new GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(GroupLayout.LEADING)
            .add(panelInfoMensaje, GroupLayout.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE)
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(GroupLayout.LEADING)
            .add(panelInfoMensaje, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabbedTrazas.addTab("Info", panelInfo);

        labelDebugMensaje.setFont(new java.awt.Font("Trebuchet MS", 0, 11));
        labelDebugMensaje.setText("CONTENIDO DEL MENSAJE");

        areaDebugMensaje.setColumns(20);
        areaDebugMensaje.setEditable(false);
        areaDebugMensaje.setRows(5);
        jScrollPane6.setViewportView(areaDebugMensaje);

        GroupLayout panelDebugMensajeLayout = new GroupLayout(panelDebugMensaje);
        panelDebugMensaje.setLayout(panelDebugMensajeLayout);
        panelDebugMensajeLayout.setHorizontalGroup(
            panelDebugMensajeLayout.createParallelGroup(GroupLayout.LEADING)
            .add(GroupLayout.TRAILING, panelDebugMensajeLayout.createSequentialGroup()
                .add(panelDebugMensajeLayout.createParallelGroup(GroupLayout.TRAILING)
                    .add(jScrollPane6, GroupLayout.LEADING, GroupLayout.DEFAULT_SIZE, 565)
                    .add(labelDebugMensaje, GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelDebugMensajeLayout.setVerticalGroup(
            panelDebugMensajeLayout.createParallelGroup(GroupLayout.LEADING)
            .add(panelDebugMensajeLayout.createSequentialGroup()
                .add(labelDebugMensaje)
                .addPreferredGap(LayoutStyle.UNRELATED)
                .add(jScrollPane6, GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))
        );

        GroupLayout panelDebugLayout = new GroupLayout(panelDebug);
        panelDebug.setLayout(panelDebugLayout);
        panelDebugLayout.setHorizontalGroup(
            panelDebugLayout.createParallelGroup(GroupLayout.LEADING)
            .add(panelDebugMensaje, GroupLayout.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE)
        );
        panelDebugLayout.setVerticalGroup(
            panelDebugLayout.createParallelGroup(GroupLayout.LEADING)
            .add(panelDebugMensaje, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabbedTrazas.addTab("Debug", panelDebug);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 11));
        jLabel8.setText("CONTENIDO DEL MENSAJE");

        areaErrorMensaje.setColumns(20);
        areaErrorMensaje.setEditable(false);
        areaErrorMensaje.setRows(5);
        jScrollPane8.setViewportView(areaErrorMensaje);

        GroupLayout panelErrorMensajeLayout = new GroupLayout(panelErrorMensaje);
        panelErrorMensaje.setLayout(panelErrorMensajeLayout);
        panelErrorMensajeLayout.setHorizontalGroup(
            panelErrorMensajeLayout.createParallelGroup(GroupLayout.LEADING)
            .add(GroupLayout.TRAILING, panelErrorMensajeLayout.createSequentialGroup()
                .add(panelErrorMensajeLayout.createParallelGroup(GroupLayout.TRAILING)
                    .add(jScrollPane8, GroupLayout.LEADING, GroupLayout.DEFAULT_SIZE, 565)
                    .add(jLabel8, GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelErrorMensajeLayout.setVerticalGroup(
            panelErrorMensajeLayout.createParallelGroup(GroupLayout.LEADING)
            .add(panelErrorMensajeLayout.createSequentialGroup()
                .add(jLabel8)
                .addPreferredGap(LayoutStyle.UNRELATED)
                .add(jScrollPane8, GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))
        );

        GroupLayout panelErrorLayout = new GroupLayout(panelError);
        panelError.setLayout(panelErrorLayout);
        panelErrorLayout.setHorizontalGroup(
            panelErrorLayout.createParallelGroup(GroupLayout.LEADING)
            .add(panelErrorMensaje, GroupLayout.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE)
        );
        panelErrorLayout.setVerticalGroup(
            panelErrorLayout.createParallelGroup(GroupLayout.LEADING)
            .add(panelErrorMensaje, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabbedTrazas.addTab("Error", panelError);

        labelFatalMensaje.setFont(new java.awt.Font("Trebuchet MS", 0, 11));
        labelFatalMensaje.setText("CONTENIDO DEL MENSAJE");

        areaFatalMensaje.setColumns(20);
        areaFatalMensaje.setEditable(false);
        areaFatalMensaje.setLineWrap(true);
        areaFatalMensaje.setRows(5);
        jScrollPane10.setViewportView(areaFatalMensaje);

        GroupLayout panelFatalMensajeLayout = new GroupLayout(panelFatalMensaje);
        panelFatalMensaje.setLayout(panelFatalMensajeLayout);
        panelFatalMensajeLayout.setHorizontalGroup(
            panelFatalMensajeLayout.createParallelGroup(GroupLayout.LEADING)
            .add(GroupLayout.TRAILING, panelFatalMensajeLayout.createSequentialGroup()
                .add(panelFatalMensajeLayout.createParallelGroup(GroupLayout.TRAILING)
                    .add(jScrollPane10, GroupLayout.LEADING, GroupLayout.DEFAULT_SIZE, 565)
                    .add(labelFatalMensaje, GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelFatalMensajeLayout.setVerticalGroup(
            panelFatalMensajeLayout.createParallelGroup(GroupLayout.LEADING)
            .add(panelFatalMensajeLayout.createSequentialGroup()
                .add(labelFatalMensaje)
                .addPreferredGap(LayoutStyle.UNRELATED)
                .add(jScrollPane10, GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))
        );

        GroupLayout panelFatalLayout = new GroupLayout(panelFatal);
        panelFatal.setLayout(panelFatalLayout);
        panelFatalLayout.setHorizontalGroup(
            panelFatalLayout.createParallelGroup(GroupLayout.LEADING)
            .add(panelFatalMensaje, GroupLayout.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE)
        );
        panelFatalLayout.setVerticalGroup(
            panelFatalLayout.createParallelGroup(GroupLayout.LEADING)
            .add(panelFatalMensaje, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabbedTrazas.addTab("Fatal", panelFatal);

        labelElegirComponente.setFont(new java.awt.Font("Trebuchet MS", 0, 11));
        labelElegirComponente.setText("Doble click en el componente a trazar:");
        
        String[] componentesTrazables = new String[elementosTrazables.size()];
        for(int i=0;i<elementosTrazables.size();i++){
        	componentesTrazables[i] = elementosTrazables.get(i);
        }
        //listaComponentes.setModel(new javax.swing.DefaultComboBoxModel(componentesTrazables));
        
      
        botonTerminar.setText("Terminar");
        botonTerminar.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				botonTerminarActionPerformed(evt);
			}
        });

        GroupLayout panelComponentesLayout = new GroupLayout(panelAdministracion);
        panelAdministracion.setLayout(panelComponentesLayout);
        panelComponentesLayout.setHorizontalGroup(
            panelComponentesLayout.createParallelGroup(GroupLayout.LEADING)
            .add(labelElegirComponente, GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
            .add(jScrollPanelComponentes, 0, 189, Short.MAX_VALUE)
            .add(panelComponentesLayout.createSequentialGroup()
                .add(54, 54, 54)
                
                
                .addContainerGap(75, Short.MAX_VALUE))
            .add(panelComponentesLayout.createSequentialGroup()
            		.add(51, 51, 51)
                    .add(botonTerminar)
                    
                    .addContainerGap(75, Short.MAX_VALUE))
            
        );
        panelComponentesLayout.setVerticalGroup(
            panelComponentesLayout.createParallelGroup(GroupLayout.LEADING)
            .add(panelComponentesLayout.createSequentialGroup()
                .add(labelElegirComponente)
                .add(35, 35, 35)
                .add(jScrollPanelComponentes, GroupLayout.PREFERRED_SIZE, 150, 150)
                .addContainerGap(50,50)
                                .add(botonTerminar))
                
             //   .addContainerGap(318, Short.MAX_VALUE))
                
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.LEADING)
            .add(labelVentana, GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
            .add(separadorZonas, GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(tabbedTrazas, GroupLayout.PREFERRED_SIZE, 580, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.UNRELATED)
                .add(panelAdministracion, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(labelVentana, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.UNRELATED)
                .add(separadorZonas, GroupLayout.PREFERRED_SIZE, 2, GroupLayout.PREFERRED_SIZE)
                .add(layout.createParallelGroup(GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(LayoutStyle.UNRELATED)
                        .add(tabbedTrazas, GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(33, 33, 33)
                        .add(panelAdministracion, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>

    private void botonElegirActionPerformed(java.awt.event.ActionEvent evt) {
    	controlador.muestraVentanaEspecifica(listaComponentes.getSelectedValue().toString());
    }
    
    private void botonTerminarActionPerformed(java.awt.event.ActionEvent evt) {
    	controlador.pedirTerminacionOrganizacion();
    }
       public void muestraMensaje(InfoTraza traza){
	   	   
    	String nivel = "";
    	Color c = new Color(0);
    	Font f = new Font("Trebuchet",Font.PLAIN,14);
    	
    	if (traza.getNivel() == InfoTraza.NivelTraza.debug){
    		nivel = "DEBUG";
    		c = Color.LIGHT_GRAY;
    		
    		areaDebugMensaje.setFont(f);
    		areaDebugMensaje.setForeground(c);
    		areaDebugMensaje.append(traza.getNombre()+"\t"+traza.getMensaje()+"\n");
    		/*
    		areaDebugMensaje.setText(areaDebugMensaje.getText()+"\n"+
    				traza.getNombre()+"\t"+traza.getMensaje());
    		*/
    	}
    	else if (traza.getNivel() == InfoTraza.NivelTraza.info){
    		nivel = "INFO";
    		c = Color.BLUE;
    		areaInfoMensaje.setFont(f);
    		areaInfoMensaje.setForeground(c);
    		areaInfoMensaje.append(traza.getNombre()+"\t"+traza.getMensaje()+"\n");
    		areaGeneralMensaje.append(traza.getNombre()+"\t"+traza.getMensaje()+"\n");
    		/*
    		areaInfoMensaje.setText(areaInfoMensaje.getText()+"\n"+
    				traza.getNombre()+"\t"+traza.getMensaje());*/
    	}
    	else if (traza.getNivel() == InfoTraza.NivelTraza.error){
    		nivel = "ERROR";
    		c = Color.RED;
    		areaErrorMensaje.setFont(f);
    		areaErrorMensaje.setForeground(c);
    		areaErrorMensaje.append(traza.getNombre()+"\t"+traza.getMensaje()+"\n");
    		areaGeneralMensaje.append(traza.getNombre()+"\t"+traza.getMensaje()+"\n");
    		/*areaErrorMensaje.setText(areaErrorMensaje.getText()+"\n"+
    				traza.getNombre()+"\t"+traza.getMensaje());
    				*/
    	}
    	else { //fatal
    		nivel = "FATAL";
    		c = Color.DARK_GRAY;
    		areaFatalMensaje.setFont(f);
    		areaFatalMensaje.setForeground(c);
    		areaFatalMensaje.append(traza.getNombre()+"\t"+traza.getMensaje()+"\n");
    		areaGeneralMensaje.append(traza.getNombre()+"\t"+traza.getMensaje()+"\n");
    		/*areaFatalMensaje.setText(areaFatalMensaje.getText()+"\n"+
    				traza.getNombre()+"\t"+traza.getMensaje());*/
    	}
    	/*
		c = Color.BLACK;  	
    	
    	areaGeneralMensaje.setFont(f);
    	areaGeneralMensaje.setForeground(c);
    	areaGeneralMensaje.setText(areaGeneralMensaje.getText()+"\n"+
    			traza.getNombre()+"\t"+traza.getMensaje());
    	*/
    }
    
    public void cierraVentana(){
    	this.controlador.cierraVentanaPrincipal();
    }
    
    // Variables declaration - do not modify
    private javax.swing.JTextArea areaDebugMensaje;
    private javax.swing.JTextArea areaErrorMensaje;
    private javax.swing.JTextArea areaFatalMensaje;
    private javax.swing.JTextArea areaGeneralMensaje;
    private javax.swing.JTextArea areaInfoMensaje;
    
    private javax.swing.JScrollPane jScrollPanelComponentes;
    private javax.swing.JList listaComponentes;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel labelDebugMensaje;
    private javax.swing.JLabel labelElegirComponente;
    private javax.swing.JLabel labelFatalMensaje;
    private javax.swing.JLabel labelGeneralMensaje;
    private javax.swing.JLabel labelInfoMensaje;
    private javax.swing.JLabel labelVentana;
    private javax.swing.JPanel panelDebug;
    private javax.swing.JPanel panelDebugMensaje;
    private javax.swing.JPanel panelAdministracion;
    private javax.swing.JPanel panelError;
    private javax.swing.JPanel panelErrorMensaje;
    private javax.swing.JPanel panelFatal;
    private javax.swing.JPanel panelFatalMensaje;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JPanel panelGeneralMensaje;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelInfoMensaje;
    private javax.swing.JSeparator separadorZonas;
    private javax.swing.JTabbedPane tabbedTrazas;
    
    private javax.swing.JButton botonTerminar;
    // End of variables declaration
    
}
