#include "EntidadesBasicas.idl"


module organizacion {
	module infraestructura {
		module corba {
			module patronAgenteCognitivo {
				module iPercepcionAgenteCognitivoIDL {
 					interface IPercepcionAgenteCognitivoIDL {
 						void aceptaEvento(in organizacion::infraestructura::corba::entidadesbasicas::eventoStruct::EventoStruct evento);
 						void aceptaMensaje(in organizacion::infraestructura::corba::entidadesbasicas::mensajeStruct::MensajeStruct evento);
 					};
 				};
 			};
 		};
	};
};
