module organizacion {
	module infraestructura {
		module corba {
			module patronRecursoSimple {
				module itfUsoRecursoSimpleIDL {
					interface ItfUsoRecursoSimpleIDL {
					};
				};
			};
		};
	};
};
