package icaro.infraestructura.corba.patronAgenteReactivo.itfUsoAgenteReactivoIDL;


/**
* organizacion/infraestructura/corba/patronAgenteReactivo/itfUsoAgenteReactivoIDL/_ItfUsoAgenteReactivoIDLStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoAgenteReactivoIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public class _ItfUsoAgenteReactivoIDLStub extends org.omg.CORBA.portable.ObjectImpl implements icaro.infraestructura.corba.patronAgenteReactivo.itfUsoAgenteReactivoIDL.ItfUsoAgenteReactivoIDL
{

  public void aceptaEvento (icaro.infraestructura.corba.entidadesbasicas.eventoStruct.EventoStruct ev)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("aceptaEvento", true);
                icaro.infraestructura.corba.entidadesbasicas.eventoStruct.EventoStructHelper.write ($out, ev);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                aceptaEvento (ev        );
            } finally {
                _releaseReply ($in);
            }
  } // aceptaEvento

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:organizacion/infraestructura/corba/patronAgenteReactivo/itfUsoAgenteReactivoIDL/ItfUsoAgenteReactivoIDL:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _ItfUsoAgenteReactivoIDLStub
