package icaro.infraestructura.corba.patronAgenteReactivo.itfUsoAgenteReactivoIDL;


/**
* organizacion/infraestructura/corba/patronAgenteReactivo/itfUsoAgenteReactivoIDL/_ItfUsoAgenteReactivoIDLImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoAgenteReactivoIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public abstract class _ItfUsoAgenteReactivoIDLImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements icaro.infraestructura.corba.patronAgenteReactivo.itfUsoAgenteReactivoIDL.ItfUsoAgenteReactivoIDL, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _ItfUsoAgenteReactivoIDLImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("aceptaEvento", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // organizacion/infraestructura/corba/patronAgenteReactivo/itfUsoAgenteReactivoIDL/ItfUsoAgenteReactivoIDL/aceptaEvento
       {
         icaro.infraestructura.corba.entidadesbasicas.eventoStruct.EventoStruct ev = icaro.infraestructura.corba.entidadesbasicas.eventoStruct.EventoStructHelper.read (in);
         this.aceptaEvento (ev);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:organizacion/infraestructura/corba/patronAgenteReactivo/itfUsoAgenteReactivoIDL/ItfUsoAgenteReactivoIDL:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _ItfUsoAgenteReactivoIDLImplBase
