package icaro.infraestructura.corba.patronAgenteReactivo.itfUsoAgenteReactivoIDL;


/**
* organizacion/infraestructura/corba/patronAgenteReactivo/itfUsoAgenteReactivoIDL/ItfUsoAgenteReactivoIDLOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoAgenteReactivoIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public interface ItfUsoAgenteReactivoIDLOperations 
{
  void aceptaEvento (icaro.infraestructura.corba.entidadesbasicas.eventoStruct.EventoStruct ev);
} // interface ItfUsoAgenteReactivoIDLOperations
