package icaro.infraestructura.corba.patronAgenteReactivo.itfUsoAgenteReactivoIDL;

/**
* organizacion/infraestructura/corba/patronAgenteReactivo/itfUsoAgenteReactivoIDL/ItfUsoAgenteReactivoIDLHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoAgenteReactivoIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public final class ItfUsoAgenteReactivoIDLHolder implements org.omg.CORBA.portable.Streamable
{
  public icaro.infraestructura.corba.patronAgenteReactivo.itfUsoAgenteReactivoIDL.ItfUsoAgenteReactivoIDL value = null;

  public ItfUsoAgenteReactivoIDLHolder ()
  {
  }

  public ItfUsoAgenteReactivoIDLHolder (icaro.infraestructura.corba.patronAgenteReactivo.itfUsoAgenteReactivoIDL.ItfUsoAgenteReactivoIDL initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = icaro.infraestructura.corba.patronAgenteReactivo.itfUsoAgenteReactivoIDL.ItfUsoAgenteReactivoIDLHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    icaro.infraestructura.corba.patronAgenteReactivo.itfUsoAgenteReactivoIDL.ItfUsoAgenteReactivoIDLHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return icaro.infraestructura.corba.patronAgenteReactivo.itfUsoAgenteReactivoIDL.ItfUsoAgenteReactivoIDLHelper.type ();
  }

}
