package icaro.infraestructura.corba.patronAgenteReactivo.itfUsoAgenteReactivoIDL;

import organizacion.infraestructura.corba.patronAgenteReactivo.itfUsoAgenteReactivoIDL.ItfUsoAgenteReactivoIDLOperations;


/**
* organizacion/infraestructura/corba/patronAgenteReactivo/itfUsoAgenteReactivoIDL/ItfUsoAgenteReactivoIDL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoAgenteReactivoIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public interface ItfUsoAgenteReactivoIDL extends ItfUsoAgenteReactivoIDLOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ItfUsoAgenteReactivoIDL
