package icaro.infraestructura.corba.patronAgenteCognitivo.iPercepcionAgenteCognitivoIDL;

import organizacion.infraestructura.corba.patronAgenteCognitivo.iPercepcionAgenteCognitivoIDL.IPercepcionAgenteCognitivoIDLOperations;


/**
* organizacion/infraestructura/corba/patronAgenteCognitivo/iPercepcionAgenteCognitivoIDL/IPercepcionAgenteCognitivoIDL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/IPercepcionAgenteCognitivo.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public interface IPercepcionAgenteCognitivoIDL extends IPercepcionAgenteCognitivoIDLOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IPercepcionAgenteCognitivoIDL
