package icaro.infraestructura.corba.patronAgenteCognitivo.iPercepcionAgenteCognitivoIDL;


/**
* organizacion/infraestructura/corba/patronAgenteCognitivo/iPercepcionAgenteCognitivoIDL/IPercepcionAgenteCognitivoIDLOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/IPercepcionAgenteCognitivo.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public interface IPercepcionAgenteCognitivoIDLOperations 
{
  void aceptaEvento (icaro.infraestructura.corba.entidadesbasicas.eventoStruct.EventoStruct evento);
  void aceptaMensaje (icaro.infraestructura.corba.entidadesbasicas.mensajeStruct.MensajeStruct evento);
} // interface IPercepcionAgenteCognitivoIDLOperations
