package icaro.infraestructura.corba.recursos.itfUsoRecInformacionUsuarioIDL;


/**
* organizacion/infraestructura/corba/recursos/itfUsoRecInformacionUsuarioIDL/_ItfUsoRecInformacionUsuarioIDLImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoRecInformacionUsuarioIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public abstract class _ItfUsoRecInformacionUsuarioIDLImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements icaro.infraestructura.corba.recursos.itfUsoRecInformacionUsuarioIDL.ItfUsoRecInformacionUsuarioIDL, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _ItfUsoRecInformacionUsuarioIDLImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("guardarMensaje", new java.lang.Integer (0));
    _methods.put ("anyadirAlternativaAlMensaje", new java.lang.Integer (1));
    _methods.put ("eliminarMensaje", new java.lang.Integer (2));
    _methods.put ("eliminarAlternativaMensaje", new java.lang.Integer (3));
    _methods.put ("obtenerMensaje", new java.lang.Integer (4));
    _methods.put ("obtenerMensajeAlternativo", new java.lang.Integer (5));
    _methods.put ("obtenerMensajeParametrizado", new java.lang.Integer (6));
    _methods.put ("obtenerMensajeAlternativoParametrizado", new java.lang.Integer (7));
    _methods.put ("obtenerTodosLosMensajes", new java.lang.Integer (8));
    _methods.put ("dameTablaDatosMostrar", new java.lang.Integer (9));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // organizacion/infraestructura/corba/recursos/itfUsoRecInformacionUsuarioIDL/ItfUsoRecInformacionUsuarioIDL/guardarMensaje
       {
         String mensaje = in.read_wstring ();
         this.guardarMensaje (mensaje);
         out = $rh.createReply();
         break;
       }

       case 1:  // organizacion/infraestructura/corba/recursos/itfUsoRecInformacionUsuarioIDL/ItfUsoRecInformacionUsuarioIDL/anyadirAlternativaAlMensaje
       {
         String id = in.read_string ();
         String alternativa = in.read_string ();
         this.anyadirAlternativaAlMensaje (id, alternativa);
         out = $rh.createReply();
         break;
       }

       case 2:  // organizacion/infraestructura/corba/recursos/itfUsoRecInformacionUsuarioIDL/ItfUsoRecInformacionUsuarioIDL/eliminarMensaje
       {
         String id = in.read_string ();
         this.eliminarMensaje (id);
         out = $rh.createReply();
         break;
       }

       case 3:  // organizacion/infraestructura/corba/recursos/itfUsoRecInformacionUsuarioIDL/ItfUsoRecInformacionUsuarioIDL/eliminarAlternativaMensaje
       {
         String id = in.read_string ();
         int alternativa = in.read_long ();
         this.eliminarAlternativaMensaje (id, alternativa);
         out = $rh.createReply();
         break;
       }

       case 4:  // organizacion/infraestructura/corba/recursos/itfUsoRecInformacionUsuarioIDL/ItfUsoRecInformacionUsuarioIDL/obtenerMensaje
       {
         String idMensaje = in.read_string ();
         String $result = null;
         $result = this.obtenerMensaje (idMensaje);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 5:  // organizacion/infraestructura/corba/recursos/itfUsoRecInformacionUsuarioIDL/ItfUsoRecInformacionUsuarioIDL/obtenerMensajeAlternativo
       {
         String idMensaje = in.read_string ();
         int numAlternativa = in.read_long ();
         String $result = null;
         $result = this.obtenerMensajeAlternativo (idMensaje, numAlternativa);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 6:  // organizacion/infraestructura/corba/recursos/itfUsoRecInformacionUsuarioIDL/ItfUsoRecInformacionUsuarioIDL/obtenerMensajeParametrizado
       {
         String idMensaje = in.read_string ();
         String parametros = in.read_wstring ();
         String $result = null;
         $result = this.obtenerMensajeParametrizado (idMensaje, parametros);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 7:  // organizacion/infraestructura/corba/recursos/itfUsoRecInformacionUsuarioIDL/ItfUsoRecInformacionUsuarioIDL/obtenerMensajeAlternativoParametrizado
       {
         String idMensaje = in.read_string ();
         String parametros = in.read_wstring ();
         int numAlternativa = in.read_long ();
         String $result = null;
         $result = this.obtenerMensajeAlternativoParametrizado (idMensaje, parametros, numAlternativa);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 8:  // organizacion/infraestructura/corba/recursos/itfUsoRecInformacionUsuarioIDL/ItfUsoRecInformacionUsuarioIDL/obtenerTodosLosMensajes
       {
         String $result = null;
         $result = this.obtenerTodosLosMensajes ();
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 9:  // organizacion/infraestructura/corba/recursos/itfUsoRecInformacionUsuarioIDL/ItfUsoRecInformacionUsuarioIDL/dameTablaDatosMostrar
       {
         String $result = null;
         $result = this.dameTablaDatosMostrar ();
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:organizacion/infraestructura/corba/recursos/itfUsoRecInformacionUsuarioIDL/ItfUsoRecInformacionUsuarioIDL:1.0", 
    "IDL:organizacion/infraestructura/corba/patronRecursoSimple/itfUsoRecursoSimpleIDL/ItfUsoRecursoSimpleIDL:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _ItfUsoRecInformacionUsuarioIDLImplBase
