package icaro.infraestructura.corba.recursos.itfUsoRecInformacionUsuarioIDL;


/**
* organizacion/infraestructura/corba/recursos/itfUsoRecInformacionUsuarioIDL/ItfUsoRecInformacionUsuarioIDLOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoRecInformacionUsuarioIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public interface ItfUsoRecInformacionUsuarioIDLOperations  extends icaro.infraestructura.corba.patronRecursoSimple.itfUsoRecursoSimpleIDL.ItfUsoRecursoSimpleIDLOperations
{
  void guardarMensaje (String mensaje);
  void anyadirAlternativaAlMensaje (String id, String alternativa);
  void eliminarMensaje (String id);
  void eliminarAlternativaMensaje (String id, int alternativa);
  String obtenerMensaje (String idMensaje);
  String obtenerMensajeAlternativo (String idMensaje, int numAlternativa);
  String obtenerMensajeParametrizado (String idMensaje, String parametros);
  String obtenerMensajeAlternativoParametrizado (String idMensaje, String parametros, int numAlternativa);
  String obtenerTodosLosMensajes ();
  String dameTablaDatosMostrar ();
} // interface ItfUsoRecInformacionUsuarioIDLOperations
