package icaro.infraestructura.corba.recursos.itfUsoRecInformacionUsuarioIDL;

import organizacion.infraestructura.corba.recursos.itfUsoRecInformacionUsuarioIDL.ItfUsoRecInformacionUsuarioIDLOperations;


/**
* organizacion/infraestructura/corba/recursos/itfUsoRecInformacionUsuarioIDL/ItfUsoRecInformacionUsuarioIDL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoRecInformacionUsuarioIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public interface ItfUsoRecInformacionUsuarioIDL extends ItfUsoRecInformacionUsuarioIDLOperations, icaro.infraestructura.corba.patronRecursoSimple.itfUsoRecursoSimpleIDL.ItfUsoRecursoSimpleIDL, org.omg.CORBA.portable.IDLEntity 
{
} // interface ItfUsoRecInformacionUsuarioIDL
