//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.26 at 01:54:43 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:icaro:aplicaciones:descripcionOrganizaciones", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package icaro.infraestructura.entidadesBasicas.descEntidadesOrganizacion.jaxb;
