package icaro.infraestructura.corba.patronAgenteReactivo.itfGestionAgenteReactivoIDL;


/**
* organizacion/infraestructura/corba/patronAgenteReactivo/itfGestionAgenteReactivoIDL/_ItfGestionAgenteReactivoIDLImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfGestionAgenteReactivoIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public abstract class _ItfGestionAgenteReactivoIDLImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements icaro.infraestructura.corba.patronAgenteReactivo.itfGestionAgenteReactivoIDL.ItfGestionAgenteReactivoIDL, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _ItfGestionAgenteReactivoIDLImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("setGestorAReportar", new java.lang.Integer (0));
    _methods.put ("arranca", new java.lang.Integer (1));
    _methods.put ("continua", new java.lang.Integer (2));
    _methods.put ("obtenerEstado", new java.lang.Integer (3));
    _methods.put ("para", new java.lang.Integer (4));
    _methods.put ("termina", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // organizacion/infraestructura/corba/patronAgenteReactivo/itfGestionAgenteReactivoIDL/ItfGestionAgenteReactivoIDL/setGestorAReportar
       {
         String nombreGestor = in.read_string ();
         String conjuntoEventos = in.read_wstring ();
         this.setGestorAReportar (nombreGestor, conjuntoEventos);
         out = $rh.createReply();
         break;
       }

       case 1:  // organizacion/infraestructura/corba/interfazGestionIDL/InterfazGestionIDL/arranca
       {
         this.arranca ();
         out = $rh.createReply();
         break;
       }

       case 2:  // organizacion/infraestructura/corba/interfazGestionIDL/InterfazGestionIDL/continua
       {
         this.continua ();
         out = $rh.createReply();
         break;
       }

       case 3:  // organizacion/infraestructura/corba/interfazGestionIDL/InterfazGestionIDL/obtenerEstado
       {
         int $result = (int)0;
         $result = this.obtenerEstado ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 4:  // organizacion/infraestructura/corba/interfazGestionIDL/InterfazGestionIDL/para
       {
         this.para ();
         out = $rh.createReply();
         break;
       }

       case 5:  // organizacion/infraestructura/corba/interfazGestionIDL/InterfazGestionIDL/termina
       {
         this.termina ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:organizacion/infraestructura/corba/patronAgenteReactivo/itfGestionAgenteReactivoIDL/ItfGestionAgenteReactivoIDL:1.0", 
    "IDL:organizacion/infraestructura/corba/interfazGestionIDL/InterfazGestionIDL:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _ItfGestionAgenteReactivoIDLImplBase
