package icaro.infraestructura.corba.patronAgenteReactivo.itfGestionAgenteReactivoIDL;


/**
* organizacion/infraestructura/corba/patronAgenteReactivo/itfGestionAgenteReactivoIDL/ItfGestionAgenteReactivoIDLOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfGestionAgenteReactivoIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public interface ItfGestionAgenteReactivoIDLOperations  extends icaro.infraestructura.corba.interfazGestionIDL.InterfazGestionIDLOperations
{
  void setGestorAReportar (String nombreGestor, String conjuntoEventos);
} // interface ItfGestionAgenteReactivoIDLOperations
