package icaro.infraestructura.corba.patronAgenteReactivo.itfGestionAgenteReactivoIDL;

import organizacion.infraestructura.corba.patronAgenteReactivo.itfGestionAgenteReactivoIDL.ItfGestionAgenteReactivoIDLOperations;


/**
* organizacion/infraestructura/corba/patronAgenteReactivo/itfGestionAgenteReactivoIDL/ItfGestionAgenteReactivoIDL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfGestionAgenteReactivoIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public interface ItfGestionAgenteReactivoIDL extends ItfGestionAgenteReactivoIDLOperations, icaro.infraestructura.corba.interfazGestionIDL.InterfazGestionIDL, org.omg.CORBA.portable.IDLEntity 
{
} // interface ItfGestionAgenteReactivoIDL
