package icaro.infraestructura.corba.patronAgenteCognitivo.factoriaAgenteCognitivoIDL;

import organizacion.infraestructura.corba.patronAgenteCognitivo.factoriaAgenteCognitivoIDL.FactoriaAgenteCognitivoIDLOperations;


/**
* organizacion/infraestructura/corba/patronAgenteCognitivo/factoriaAgenteCognitivoIDL/FactoriaAgenteCognitivoIDL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/FactoriaAgenteCognitivoIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public interface FactoriaAgenteCognitivoIDL extends FactoriaAgenteCognitivoIDLOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FactoriaAgenteCognitivoIDL
