package icaro.infraestructura.corba.patronAgenteCognitivo.factoriaAgenteCognitivoIDL;


/**
* organizacion/infraestructura/corba/patronAgenteCognitivo/factoriaAgenteCognitivoIDL/FactoriaAgenteCognitivoIDLOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/FactoriaAgenteCognitivoIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public interface FactoriaAgenteCognitivoIDLOperations 
{
  void crearAgenteCognitivo (String nombreAgente);
} // interface FactoriaAgenteCognitivoIDLOperations
