package icaro.infraestructura.corba.patronAgenteCognitivo.factoriaAgenteCognitivoIDL;

/**
* organizacion/infraestructura/corba/patronAgenteCognitivo/factoriaAgenteCognitivoIDL/FactoriaAgenteCognitivoIDLHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/FactoriaAgenteCognitivoIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public final class FactoriaAgenteCognitivoIDLHolder implements org.omg.CORBA.portable.Streamable
{
  public icaro.infraestructura.corba.patronAgenteCognitivo.factoriaAgenteCognitivoIDL.FactoriaAgenteCognitivoIDL value = null;

  public FactoriaAgenteCognitivoIDLHolder ()
  {
  }

  public FactoriaAgenteCognitivoIDLHolder (icaro.infraestructura.corba.patronAgenteCognitivo.factoriaAgenteCognitivoIDL.FactoriaAgenteCognitivoIDL initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = icaro.infraestructura.corba.patronAgenteCognitivo.factoriaAgenteCognitivoIDL.FactoriaAgenteCognitivoIDLHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    icaro.infraestructura.corba.patronAgenteCognitivo.factoriaAgenteCognitivoIDL.FactoriaAgenteCognitivoIDLHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return icaro.infraestructura.corba.patronAgenteCognitivo.factoriaAgenteCognitivoIDL.FactoriaAgenteCognitivoIDLHelper.type ();
  }

}
