package icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL;


/**
* organizacion/infraestructura/corba/recursos/itfUsoRecTestPersonalidadIDL/_ItfUsoRecTestPersonalidadIDLImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoRecTestPersonalidadIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public abstract class _ItfUsoRecTestPersonalidadIDLImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL.ItfUsoRecTestPersonalidadIDL, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _ItfUsoRecTestPersonalidadIDLImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("cargaPreguntas", new java.lang.Integer (0));
    _methods.put ("anotaRespuestas", new java.lang.Integer (1));
    _methods.put ("guardarProgresoFichero", new java.lang.Integer (2));
    _methods.put ("textoResultado", new java.lang.Integer (3));
    _methods.put ("getResultados", new java.lang.Integer (4));
    _methods.put ("todasRespondidas", new java.lang.Integer (5));
    _methods.put ("reinicia", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // organizacion/infraestructura/corba/recursos/itfUsoRecTestPersonalidadIDL/ItfUsoRecTestPersonalidadIDL/cargaPreguntas
       {
         String preguntas[] = icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL.t_cadenasHelper.read (in);
         int $result[] = null;
         $result = this.cargaPreguntas (preguntas);
         out = $rh.createReply();
         icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL.t_resultadosHelper.write (out, $result);
         break;
       }

       case 1:  // organizacion/infraestructura/corba/recursos/itfUsoRecTestPersonalidadIDL/ItfUsoRecTestPersonalidadIDL/anotaRespuestas
       {
         String preguntas[] = icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL.t_cadenasHelper.read (in);
         int respuestas[] = icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL.t_resultadosHelper.read (in);
         this.anotaRespuestas (preguntas, respuestas);
         out = $rh.createReply();
         break;
       }

       case 2:  // organizacion/infraestructura/corba/recursos/itfUsoRecTestPersonalidadIDL/ItfUsoRecTestPersonalidadIDL/guardarProgresoFichero
       {
         this.guardarProgresoFichero ();
         out = $rh.createReply();
         break;
       }

       case 3:  // organizacion/infraestructura/corba/recursos/itfUsoRecTestPersonalidadIDL/ItfUsoRecTestPersonalidadIDL/textoResultado
       {
         String textos[] = icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL.t_cadenasHelper.read (in);
         String $result = null;
         $result = this.textoResultado (textos);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // organizacion/infraestructura/corba/recursos/itfUsoRecTestPersonalidadIDL/ItfUsoRecTestPersonalidadIDL/getResultados
       {
         int $result[] = null;
         $result = this.getResultados ();
         out = $rh.createReply();
         icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL.t_resultadosHelper.write (out, $result);
         break;
       }

       case 5:  // organizacion/infraestructura/corba/recursos/itfUsoRecTestPersonalidadIDL/ItfUsoRecTestPersonalidadIDL/todasRespondidas
       {
         boolean $result = false;
         $result = this.todasRespondidas ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 6:  // organizacion/infraestructura/corba/recursos/itfUsoRecTestPersonalidadIDL/ItfUsoRecTestPersonalidadIDL/reinicia
       {
         this.reinicia ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:organizacion/infraestructura/corba/recursos/itfUsoRecTestPersonalidadIDL/ItfUsoRecTestPersonalidadIDL:1.0", 
    "IDL:organizacion/infraestructura/corba/patronRecursoSimple/itfUsoRecursoSimpleIDL/ItfUsoRecursoSimpleIDL:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _ItfUsoRecTestPersonalidadIDLImplBase
