package icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL;

import organizacion.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL._ItfUsoRecTestPersonalidadIDLStub;


/**
* organizacion/infraestructura/corba/recursos/itfUsoRecTestPersonalidadIDL/ItfUsoRecTestPersonalidadIDLHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoRecTestPersonalidadIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

abstract public class ItfUsoRecTestPersonalidadIDLHelper
{
  private static String  _id = "IDL:organizacion/infraestructura/corba/recursos/itfUsoRecTestPersonalidadIDL/ItfUsoRecTestPersonalidadIDL:1.0";

  public static void insert (org.omg.CORBA.Any a, icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL.ItfUsoRecTestPersonalidadIDL that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL.ItfUsoRecTestPersonalidadIDL extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL.ItfUsoRecTestPersonalidadIDLHelper.id (), "ItfUsoRecTestPersonalidadIDL");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL.ItfUsoRecTestPersonalidadIDL read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ItfUsoRecTestPersonalidadIDLStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL.ItfUsoRecTestPersonalidadIDL value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL.ItfUsoRecTestPersonalidadIDL narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL.ItfUsoRecTestPersonalidadIDL)
      return (icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL.ItfUsoRecTestPersonalidadIDL)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL._ItfUsoRecTestPersonalidadIDLStub stub = new icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL._ItfUsoRecTestPersonalidadIDLStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL.ItfUsoRecTestPersonalidadIDL unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL.ItfUsoRecTestPersonalidadIDL)
      return (icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL.ItfUsoRecTestPersonalidadIDL)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL._ItfUsoRecTestPersonalidadIDLStub stub = new icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL._ItfUsoRecTestPersonalidadIDLStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
