package icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL;


/**
* organizacion/infraestructura/corba/recursos/itfUsoRecTestPersonalidadIDL/ItfUsoRecTestPersonalidadIDLOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoRecTestPersonalidadIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public interface ItfUsoRecTestPersonalidadIDLOperations  extends icaro.infraestructura.corba.patronRecursoSimple.itfUsoRecursoSimpleIDL.ItfUsoRecursoSimpleIDLOperations
{
  int[] cargaPreguntas (String[] preguntas);
  void anotaRespuestas (String[] preguntas, int[] respuestas);
  void guardarProgresoFichero ();
  String textoResultado (String[] textos);
  int[] getResultados ();
  boolean todasRespondidas ();
  void reinicia ();
} // interface ItfUsoRecTestPersonalidadIDLOperations
