package icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL;

/**
* organizacion/infraestructura/corba/recursos/itfUsoRecTestPersonalidadIDL/ItfUsoRecTestPersonalidadIDLHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoRecTestPersonalidadIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public final class ItfUsoRecTestPersonalidadIDLHolder implements org.omg.CORBA.portable.Streamable
{
  public icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL.ItfUsoRecTestPersonalidadIDL value = null;

  public ItfUsoRecTestPersonalidadIDLHolder ()
  {
  }

  public ItfUsoRecTestPersonalidadIDLHolder (icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL.ItfUsoRecTestPersonalidadIDL initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL.ItfUsoRecTestPersonalidadIDLHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL.ItfUsoRecTestPersonalidadIDLHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return icaro.infraestructura.corba.recursos.itfUsoRecTestPersonalidadIDL.ItfUsoRecTestPersonalidadIDLHelper.type ();
  }

}
