package icaro.infraestructura.recursosOrganizacion.recursoTrazas.imp.gui;

import icaro.infraestructura.recursosOrganizacion.recursoTrazas.imp.NotificacionesRecTrazas;
import icaro.infraestructura.recursosOrganizacion.recursoTrazas.imp.componentes.InfoTraza;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

import org.jdesktop.layout.GroupLayout;
import org.jdesktop.layout.LayoutStyle;

/**
 *
 * @author  fmpr
 */
public class PanelTrazasEspecificas extends javax.swing.JFrame {
    
//	private ControlTrazas controlador;
	
	private String nombreComponente; //identificaci�n de la ventana
    
    /** Creates new form NewJFrame */
    public PanelTrazasEspecificas(String nombre, String contenido) {
        initComponents(contenido,nombre);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.nombreComponente = nombre;
        this.setTitle(nombreComponente);
  //      this.controlador = c;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(String contenido, String nombre) {

    	this.addWindowListener(new WindowAdapter()
		{
    		public void windowClosing(WindowEvent e)
    		{
    			cierraVentana();
    		}
		});
    	
    	this.setResizable(false);
    	
        labelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTrazas = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 18));
        labelTitulo.setText("                                     "+nombre.toUpperCase());

        areaTrazas.setColumns(20);
        areaTrazas.setEditable(false);
        areaTrazas.setFont(new java.awt.Font("Trebuchet MS", 0, 14));
        areaTrazas.setRows(5);
        
        Font f = new Font("Trebuchet",Font.PLAIN,14);
    	areaTrazas.setFont(f);
    	areaTrazas.setForeground(Color.BLUE);
        areaTrazas.setText(contenido);
        
        jScrollPane1.setViewportView(areaTrazas);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.LEADING)
            
            .add(labelTitulo, GroupLayout.TRAILING, GroupLayout.DEFAULT_SIZE, 565)
            .add(jScrollPane1, GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.LEADING)
            .add(GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(labelTitulo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.RELATED)
                .add(jScrollPane1, GroupLayout.PREFERRED_SIZE, 422, GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        

    public void cierraVentana(){
   	this.setVisible(false);
    }
    
    public String getIdentificador(){
    	return nombreComponente;
    }
    
    public void muestraMensaje(InfoTraza traza){
    	   
    	String nivel = "";
    	Color c = new Color(0);
    	if (traza.getNivel() == InfoTraza.NivelTraza.debug){
    		nivel = "DEBUG";
    		c = Color.BLUE;
    	}
    	else if (traza.getNivel() == InfoTraza.NivelTraza.info){
    		nivel = "INFO";
    		c = Color.GREEN;
    	}
    	else if (traza.getNivel() == InfoTraza.NivelTraza.error){
    		nivel = "ERROR";
    		c = Color.ORANGE;
    	}
    	else { //fatal
    		nivel = "FATAL";
    		c = Color.RED;
    	}
    	Font f = new Font("Trebuchet",Font.PLAIN,14);
    	areaTrazas.setFont(f);
    	areaTrazas.setForeground(Color.BLUE);
    	//Concateno el nuevo mensaje con el que hab�a antes
        
    	areaTrazas.setText(areaTrazas.getText()+
    			nivel+" : "+traza.getMensaje()+"\n");
    	//si escribo null,borra lo anterior
    }
    
    // Variables declaration - do not modify                     
    private JTextArea areaTrazas;
    private JScrollPane jScrollPane1;
    private JLabel labelTitulo;
    // End of variables declaration                   
    
}

