package icaro.infraestructura.corba.patronRecursoSimple.ItfGestionRecursoSimpleIDL;


/**
* organizacion/infraestructura/corba/patronRecursoSimple/ItfGestionRecursoSimpleIDL/ItfGestionRecursoSimpleIDLOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfGestionRecursoSimpleIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public interface ItfGestionRecursoSimpleIDLOperations  extends icaro.infraestructura.corba.interfazGestionIDL.InterfazGestionIDLOperations
{
} // interface ItfGestionRecursoSimpleIDLOperations
