package icaro.infraestructura.corba.patronRecursoSimple.ItfGestionRecursoSimpleIDL;

import organizacion.infraestructura.corba.patronRecursoSimple.ItfGestionRecursoSimpleIDL.ItfGestionRecursoSimpleIDLOperations;


/**
* organizacion/infraestructura/corba/patronRecursoSimple/ItfGestionRecursoSimpleIDL/ItfGestionRecursoSimpleIDL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfGestionRecursoSimpleIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public interface ItfGestionRecursoSimpleIDL extends ItfGestionRecursoSimpleIDLOperations, icaro.infraestructura.corba.interfazGestionIDL.InterfazGestionIDL, org.omg.CORBA.portable.IDLEntity 
{
} // interface ItfGestionRecursoSimpleIDL
