package icaro.infraestructura.corba.recursos.visualizacion.itfUsoVisualizadorAltaIDL;


/**
* organizacion/infraestructura/corba/recursos/visualizacion/itfUsoVisualizadorAltaIDL/_ItfUsoVisualizadorAltaIDLImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoVisualizadorAccesoIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public abstract class _ItfUsoVisualizadorAltaIDLImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements icaro.infraestructura.corba.recursos.visualizacion.itfUsoVisualizadorAltaIDL.ItfUsoVisualizadorAltaIDL, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _ItfUsoVisualizadorAltaIDLImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("mostrarVisualizadorAlta", new java.lang.Integer (0));
    _methods.put ("cerrarVisualizadorAlta", new java.lang.Integer (1));
    _methods.put ("mostrarMensajeInformacion", new java.lang.Integer (2));
    _methods.put ("mostrarMensajeAviso", new java.lang.Integer (3));
    _methods.put ("mostrarMensajeError", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // organizacion/infraestructura/corba/recursos/visualizacion/itfUsoVisualizadorAltaIDL/ItfUsoVisualizadorAltaIDL/mostrarVisualizadorAlta
       {
         this.mostrarVisualizadorAlta ();
         out = $rh.createReply();
         break;
       }

       case 1:  // organizacion/infraestructura/corba/recursos/visualizacion/itfUsoVisualizadorAltaIDL/ItfUsoVisualizadorAltaIDL/cerrarVisualizadorAlta
       {
         this.cerrarVisualizadorAlta ();
         out = $rh.createReply();
         break;
       }

       case 2:  // organizacion/infraestructura/corba/recursos/visualizacion/itfUsoVisualizadorAltaIDL/ItfUsoVisualizadorAltaIDL/mostrarMensajeInformacion
       {
         String titulo = in.read_string ();
         String mensaje = in.read_string ();
         this.mostrarMensajeInformacion (titulo, mensaje);
         out = $rh.createReply();
         break;
       }

       case 3:  // organizacion/infraestructura/corba/recursos/visualizacion/itfUsoVisualizadorAltaIDL/ItfUsoVisualizadorAltaIDL/mostrarMensajeAviso
       {
         String titulo = in.read_string ();
         String mensaje = in.read_string ();
         this.mostrarMensajeAviso (titulo, mensaje);
         out = $rh.createReply();
         break;
       }

       case 4:  // organizacion/infraestructura/corba/recursos/visualizacion/itfUsoVisualizadorAltaIDL/ItfUsoVisualizadorAltaIDL/mostrarMensajeError
       {
         String titulo = in.read_string ();
         String mensaje = in.read_string ();
         this.mostrarMensajeError (titulo, mensaje);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:organizacion/infraestructura/corba/recursos/visualizacion/itfUsoVisualizadorAltaIDL/ItfUsoVisualizadorAltaIDL:1.0", 
    "IDL:organizacion/infraestructura/corba/patronRecursoSimple/itfUsoRecursoSimpleIDL/ItfUsoRecursoSimpleIDL:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _ItfUsoVisualizadorAltaIDLImplBase
