package icaro.infraestructura.corba.patronAgenteReactivo.factoriaAgenteReactivoIDL;

/**
* organizacion/infraestructura/corba/patronAgenteReactivo/factoriaAgenteReactivoIDL/FactoriaAgenteReactivoIDLHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/FactoriaAgenteReactivoIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public final class FactoriaAgenteReactivoIDLHolder implements org.omg.CORBA.portable.Streamable
{
  public icaro.infraestructura.corba.patronAgenteReactivo.factoriaAgenteReactivoIDL.FactoriaAgenteReactivoIDL value = null;

  public FactoriaAgenteReactivoIDLHolder ()
  {
  }

  public FactoriaAgenteReactivoIDLHolder (icaro.infraestructura.corba.patronAgenteReactivo.factoriaAgenteReactivoIDL.FactoriaAgenteReactivoIDL initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = icaro.infraestructura.corba.patronAgenteReactivo.factoriaAgenteReactivoIDL.FactoriaAgenteReactivoIDLHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    icaro.infraestructura.corba.patronAgenteReactivo.factoriaAgenteReactivoIDL.FactoriaAgenteReactivoIDLHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return icaro.infraestructura.corba.patronAgenteReactivo.factoriaAgenteReactivoIDL.FactoriaAgenteReactivoIDLHelper.type ();
  }

}
