package icaro.infraestructura.corba.patronAgenteReactivo.factoriaAgenteReactivoIDL;

import organizacion.infraestructura.corba.patronAgenteReactivo.factoriaAgenteReactivoIDL.FactoriaAgenteReactivoIDLOperations;


/**
* organizacion/infraestructura/corba/patronAgenteReactivo/factoriaAgenteReactivoIDL/FactoriaAgenteReactivoIDL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/FactoriaAgenteReactivoIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public interface FactoriaAgenteReactivoIDL extends FactoriaAgenteReactivoIDLOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FactoriaAgenteReactivoIDL
