package icaro.infraestructura.corba.patronAgenteReactivo.factoriaAgenteReactivoIDL;

import icaro.infraestructura.entidadesBasicas.descEntidadesOrganizacion.DescInstanciaAgente;


/**
* organizacion/infraestructura/corba/patronAgenteReactivo/factoriaAgenteReactivoIDL/FactoriaAgenteReactivoIDLOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/FactoriaAgenteReactivoIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public interface FactoriaAgenteReactivoIDLOperations 
{
  void crearAgenteReactivo (DescInstanciaAgente nombreAgente);
} // interface FactoriaAgenteReactivoIDLOperations
