package icaro.infraestructura.corba.patronRecursoSimple.factoriaRecursoSimpleIDL;


/**
* organizacion/infraestructura/corba/patronRecursoSimple/factoriaRecursoSimpleIDL/FactoriaRecursoSimpleIDLOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/FactoriaRecursoSimpleIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public interface FactoriaRecursoSimpleIDLOperations 
{
  void crearRecursoSimple (String nombreRecurso);
} // interface FactoriaRecursoSimpleIDLOperations
