package icaro.infraestructura.corba.patronRecursoSimple.factoriaRecursoSimpleIDL;

import organizacion.infraestructura.corba.patronRecursoSimple.factoriaRecursoSimpleIDL.FactoriaRecursoSimpleIDLOperations;


/**
* organizacion/infraestructura/corba/patronRecursoSimple/factoriaRecursoSimpleIDL/FactoriaRecursoSimpleIDL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/FactoriaRecursoSimpleIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public interface FactoriaRecursoSimpleIDL extends FactoriaRecursoSimpleIDLOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FactoriaRecursoSimpleIDL
