package icaro.infraestructura.corba.patronRecursoSimple.factoriaRecursoSimpleIDL;

/**
* organizacion/infraestructura/corba/patronRecursoSimple/factoriaRecursoSimpleIDL/FactoriaRecursoSimpleIDLHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/FactoriaRecursoSimpleIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public final class FactoriaRecursoSimpleIDLHolder implements org.omg.CORBA.portable.Streamable
{
  public icaro.infraestructura.corba.patronRecursoSimple.factoriaRecursoSimpleIDL.FactoriaRecursoSimpleIDL value = null;

  public FactoriaRecursoSimpleIDLHolder ()
  {
  }

  public FactoriaRecursoSimpleIDLHolder (icaro.infraestructura.corba.patronRecursoSimple.factoriaRecursoSimpleIDL.FactoriaRecursoSimpleIDL initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = icaro.infraestructura.corba.patronRecursoSimple.factoriaRecursoSimpleIDL.FactoriaRecursoSimpleIDLHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    icaro.infraestructura.corba.patronRecursoSimple.factoriaRecursoSimpleIDL.FactoriaRecursoSimpleIDLHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return icaro.infraestructura.corba.patronRecursoSimple.factoriaRecursoSimpleIDL.FactoriaRecursoSimpleIDLHelper.type ();
  }

}
