package icaro.infraestructura.corba.recursosOrganizacion.itfUsoRecursoTrazasIDL;

/**
* organizacion/infraestructura/corba/recursosOrganizacion/itfUsoRecursoTrazasIDL/ItfUsoRecursoTrazasIDLHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoRecursoTrazas.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public final class ItfUsoRecursoTrazasIDLHolder implements org.omg.CORBA.portable.Streamable
{
  public icaro.infraestructura.corba.recursosOrganizacion.itfUsoRecursoTrazasIDL.ItfUsoRecursoTrazasIDL value = null;

  public ItfUsoRecursoTrazasIDLHolder ()
  {
  }

  public ItfUsoRecursoTrazasIDLHolder (icaro.infraestructura.corba.recursosOrganizacion.itfUsoRecursoTrazasIDL.ItfUsoRecursoTrazasIDL initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = icaro.infraestructura.corba.recursosOrganizacion.itfUsoRecursoTrazasIDL.ItfUsoRecursoTrazasIDLHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    icaro.infraestructura.corba.recursosOrganizacion.itfUsoRecursoTrazasIDL.ItfUsoRecursoTrazasIDLHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return icaro.infraestructura.corba.recursosOrganizacion.itfUsoRecursoTrazasIDL.ItfUsoRecursoTrazasIDLHelper.type ();
  }

}
