package icaro.infraestructura.corba.recursosOrganizacion.itfUsoRecursoTrazasIDL;

import organizacion.infraestructura.corba.recursosOrganizacion.itfUsoRecursoTrazasIDL.ItfUsoRecursoTrazasIDLOperations;


/**
* organizacion/infraestructura/corba/recursosOrganizacion/itfUsoRecursoTrazasIDL/ItfUsoRecursoTrazasIDL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoRecursoTrazas.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public interface ItfUsoRecursoTrazasIDL extends ItfUsoRecursoTrazasIDLOperations, icaro.infraestructura.corba.patronRecursoSimple.itfUsoRecursoSimpleIDL.ItfUsoRecursoSimpleIDL, org.omg.CORBA.portable.IDLEntity 
{
} // interface ItfUsoRecursoTrazasIDL
