package icaro.infraestructura.corba.recursos.ItfUsoPersistenciaIDL;


/**
* organizacion/infraestructura/corba/recursos/ItfUsoPersistenciaIDL/_ItfUsoPersistenciaIDLImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoPersistenciaIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public abstract class _ItfUsoPersistenciaIDLImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements icaro.infraestructura.corba.recursos.ItfUsoPersistenciaIDL.ItfUsoPersistenciaIDL, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _ItfUsoPersistenciaIDLImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("compruebaUsuario", new java.lang.Integer (0));
    _methods.put ("compruebaNombreUsuario", new java.lang.Integer (1));
    _methods.put ("insertaUsuario", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // organizacion/infraestructura/corba/recursos/ItfUsoPersistenciaIDL/ItfUsoPersistenciaIDL/compruebaUsuario
       {
         String usuario = in.read_string ();
         String password = in.read_string ();
         boolean $result = false;
         $result = this.compruebaUsuario (usuario, password);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // organizacion/infraestructura/corba/recursos/ItfUsoPersistenciaIDL/ItfUsoPersistenciaIDL/compruebaNombreUsuario
       {
         String usuario = in.read_string ();
         boolean $result = false;
         $result = this.compruebaNombreUsuario (usuario);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // organizacion/infraestructura/corba/recursos/ItfUsoPersistenciaIDL/ItfUsoPersistenciaIDL/insertaUsuario
       {
         String usuario = in.read_string ();
         String password = in.read_string ();
         this.insertaUsuario (usuario, password);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:organizacion/infraestructura/corba/recursos/ItfUsoPersistenciaIDL/ItfUsoPersistenciaIDL:1.0", 
    "IDL:organizacion/infraestructura/corba/patronRecursoSimple/itfUsoRecursoSimpleIDL/ItfUsoRecursoSimpleIDL:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _ItfUsoPersistenciaIDLImplBase
