package icaro.infraestructura.corba.recursos.ItfUsoPersistenciaIDL;


/**
* organizacion/infraestructura/corba/recursos/ItfUsoPersistenciaIDL/_ItfUsoPersistenciaIDLStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoPersistenciaIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public class _ItfUsoPersistenciaIDLStub extends org.omg.CORBA.portable.ObjectImpl implements icaro.infraestructura.corba.recursos.ItfUsoPersistenciaIDL.ItfUsoPersistenciaIDL
{

  public boolean compruebaUsuario (String usuario, String password)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("compruebaUsuario", true);
                $out.write_string (usuario);
                $out.write_string (password);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return compruebaUsuario (usuario, password        );
            } finally {
                _releaseReply ($in);
            }
  } // compruebaUsuario

  public boolean compruebaNombreUsuario (String usuario)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("compruebaNombreUsuario", true);
                $out.write_string (usuario);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return compruebaNombreUsuario (usuario        );
            } finally {
                _releaseReply ($in);
            }
  } // compruebaNombreUsuario

  public void insertaUsuario (String usuario, String password)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("insertaUsuario", true);
                $out.write_string (usuario);
                $out.write_string (password);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                insertaUsuario (usuario, password        );
            } finally {
                _releaseReply ($in);
            }
  } // insertaUsuario

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:organizacion/infraestructura/corba/recursos/ItfUsoPersistenciaIDL/ItfUsoPersistenciaIDL:1.0", 
    "IDL:organizacion/infraestructura/corba/patronRecursoSimple/itfUsoRecursoSimpleIDL/ItfUsoRecursoSimpleIDL:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _ItfUsoPersistenciaIDLStub
