package icaro.infraestructura.corba.recursos.ItfUsoPersistenciaIDL;


/**
* organizacion/infraestructura/corba/recursos/ItfUsoPersistenciaIDL/ItfUsoPersistenciaIDLOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoPersistenciaIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public interface ItfUsoPersistenciaIDLOperations  extends icaro.infraestructura.corba.patronRecursoSimple.itfUsoRecursoSimpleIDL.ItfUsoRecursoSimpleIDLOperations
{
  boolean compruebaUsuario (String usuario, String password);
  boolean compruebaNombreUsuario (String usuario);
  void insertaUsuario (String usuario, String password);
} // interface ItfUsoPersistenciaIDLOperations
