package icaro.infraestructura.corba.recursos.ItfUsoPersistenciaIDL;

import organizacion.infraestructura.corba.recursos.ItfUsoPersistenciaIDL.ItfUsoPersistenciaIDLOperations;


/**
* organizacion/infraestructura/corba/recursos/ItfUsoPersistenciaIDL/ItfUsoPersistenciaIDL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoPersistenciaIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public interface ItfUsoPersistenciaIDL extends ItfUsoPersistenciaIDLOperations, icaro.infraestructura.corba.patronRecursoSimple.itfUsoRecursoSimpleIDL.ItfUsoRecursoSimpleIDL, org.omg.CORBA.portable.IDLEntity 
{
} // interface ItfUsoPersistenciaIDL
