package icaro.infraestructura.corba.interfazGestionIDL;

import organizacion.infraestructura.corba.interfazGestionIDL._InterfazGestionIDLStub;


/**
* organizacion/infraestructura/corba/interfazGestionIDL/InterfazGestionIDLHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/InterfazGestionIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

abstract public class InterfazGestionIDLHelper
{
  private static String  _id = "IDL:organizacion/infraestructura/corba/interfazGestionIDL/InterfazGestionIDL:1.0";

  public static void insert (org.omg.CORBA.Any a, icaro.infraestructura.corba.interfazGestionIDL.InterfazGestionIDL that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static icaro.infraestructura.corba.interfazGestionIDL.InterfazGestionIDL extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (icaro.infraestructura.corba.interfazGestionIDL.InterfazGestionIDLHelper.id (), "InterfazGestionIDL");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static icaro.infraestructura.corba.interfazGestionIDL.InterfazGestionIDL read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_InterfazGestionIDLStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, icaro.infraestructura.corba.interfazGestionIDL.InterfazGestionIDL value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static icaro.infraestructura.corba.interfazGestionIDL.InterfazGestionIDL narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof icaro.infraestructura.corba.interfazGestionIDL.InterfazGestionIDL)
      return (icaro.infraestructura.corba.interfazGestionIDL.InterfazGestionIDL)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      icaro.infraestructura.corba.interfazGestionIDL._InterfazGestionIDLStub stub = new icaro.infraestructura.corba.interfazGestionIDL._InterfazGestionIDLStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static icaro.infraestructura.corba.interfazGestionIDL.InterfazGestionIDL unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof icaro.infraestructura.corba.interfazGestionIDL.InterfazGestionIDL)
      return (icaro.infraestructura.corba.interfazGestionIDL.InterfazGestionIDL)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      icaro.infraestructura.corba.interfazGestionIDL._InterfazGestionIDLStub stub = new icaro.infraestructura.corba.interfazGestionIDL._InterfazGestionIDLStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
