package icaro.infraestructura.corba.interfazGestionIDL;


/**
* organizacion/infraestructura/corba/interfazGestionIDL/InterfazGestionIDLOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/InterfazGestionIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public interface InterfazGestionIDLOperations 
{
  void arranca ();
  void continua ();
  int obtenerEstado ();
  void para ();
  void termina ();
} // interface InterfazGestionIDLOperations
