package icaro.infraestructura.corba.interfazGestionIDL;

/**
* organizacion/infraestructura/corba/interfazGestionIDL/InterfazGestionIDLHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/InterfazGestionIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public final class InterfazGestionIDLHolder implements org.omg.CORBA.portable.Streamable
{
  public icaro.infraestructura.corba.interfazGestionIDL.InterfazGestionIDL value = null;

  public InterfazGestionIDLHolder ()
  {
  }

  public InterfazGestionIDLHolder (icaro.infraestructura.corba.interfazGestionIDL.InterfazGestionIDL initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = icaro.infraestructura.corba.interfazGestionIDL.InterfazGestionIDLHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    icaro.infraestructura.corba.interfazGestionIDL.InterfazGestionIDLHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return icaro.infraestructura.corba.interfazGestionIDL.InterfazGestionIDLHelper.type ();
  }

}
