package icaro.infraestructura.corba.interfazGestionIDL;

import organizacion.infraestructura.corba.interfazGestionIDL.InterfazGestionIDLOperations;


/**
* organizacion/infraestructura/corba/interfazGestionIDL/InterfazGestionIDL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/InterfazGestionIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public interface InterfazGestionIDL extends InterfazGestionIDLOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface InterfazGestionIDL
