package icaro.infraestructura.corba.recursosOrganizacion.itfUsoRecursoTrazasIDL.infoTrazaStruct;


/**
* organizacion/infraestructura/corba/recursosOrganizacion/itfUsoRecursoTrazasIDL/infoTrazaStruct/InfoTrazaStruct.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoRecursoTrazas.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public final class InfoTrazaStruct implements org.omg.CORBA.portable.IDLEntity
{
  public String entidadEmisora = null;
  public String mensaje = null;
  public icaro.infraestructura.corba.recursosOrganizacion.itfUsoRecursoTrazasIDL.infoTrazaStruct.NivelTrazaIDL nivel = null;

  public InfoTrazaStruct ()
  {
  } // ctor

  public InfoTrazaStruct (String _entidadEmisora, String _mensaje, icaro.infraestructura.corba.recursosOrganizacion.itfUsoRecursoTrazasIDL.infoTrazaStruct.NivelTrazaIDL _nivel)
  {
    entidadEmisora = _entidadEmisora;
    mensaje = _mensaje;
    nivel = _nivel;
  } // ctor

} // class InfoTrazaStruct
