package icaro.infraestructura.corba.recursosOrganizacion.itfUsoRecursoTrazasIDL.infoTrazaStruct;


/**
* organizacion/infraestructura/corba/recursosOrganizacion/itfUsoRecursoTrazasIDL/infoTrazaStruct/NivelTrazaIDL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoRecursoTrazas.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public class NivelTrazaIDL implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static icaro.infraestructura.corba.recursosOrganizacion.itfUsoRecursoTrazasIDL.infoTrazaStruct.NivelTrazaIDL[] __array = new icaro.infraestructura.corba.recursosOrganizacion.itfUsoRecursoTrazasIDL.infoTrazaStruct.NivelTrazaIDL [__size];

  public static final int _error = 0;
  public static final icaro.infraestructura.corba.recursosOrganizacion.itfUsoRecursoTrazasIDL.infoTrazaStruct.NivelTrazaIDL error = new icaro.infraestructura.corba.recursosOrganizacion.itfUsoRecursoTrazasIDL.infoTrazaStruct.NivelTrazaIDL(_error);
  public static final int _info = 1;
  public static final icaro.infraestructura.corba.recursosOrganizacion.itfUsoRecursoTrazasIDL.infoTrazaStruct.NivelTrazaIDL info = new icaro.infraestructura.corba.recursosOrganizacion.itfUsoRecursoTrazasIDL.infoTrazaStruct.NivelTrazaIDL(_info);
  public static final int _debug = 2;
  public static final icaro.infraestructura.corba.recursosOrganizacion.itfUsoRecursoTrazasIDL.infoTrazaStruct.NivelTrazaIDL debug = new icaro.infraestructura.corba.recursosOrganizacion.itfUsoRecursoTrazasIDL.infoTrazaStruct.NivelTrazaIDL(_debug);
  public static final int _fatal = 3;
  public static final icaro.infraestructura.corba.recursosOrganizacion.itfUsoRecursoTrazasIDL.infoTrazaStruct.NivelTrazaIDL fatal = new icaro.infraestructura.corba.recursosOrganizacion.itfUsoRecursoTrazasIDL.infoTrazaStruct.NivelTrazaIDL(_fatal);

  public int value ()
  {
    return __value;
  }

  public static icaro.infraestructura.corba.recursosOrganizacion.itfUsoRecursoTrazasIDL.infoTrazaStruct.NivelTrazaIDL from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected NivelTrazaIDL (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class NivelTrazaIDL
