package icaro.infraestructura.corba.patronRecursoSimple.itfUsoRecursoSimpleIDL;


/**
* organizacion/infraestructura/corba/patronRecursoSimple/itfUsoRecursoSimpleIDL/ItfUsoRecursoSimpleIDLOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Documents and Settings/damiano/Escritorio/workspace/OrganizacionCognitivo-CORBA/idls/ItfUsoRecursoSimpleIDL.idl
* viernes 13 de junio de 2008 11H12' CEST
*/

public interface ItfUsoRecursoSimpleIDLOperations 
{
} // interface ItfUsoRecursoSimpleIDLOperations
